# Stage 1: Use an official minimalistic Alpine image of Node with a specified version
FROM node:20-alpine as build
# Set the working directory
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install Angular CLI globally
RUN npm install -g @angular/cli
# Install production dependencies
RUN npm install
# Copy the source code into the build image
COPY . .
# Build the Angular application
RUN npm run build
# Stage 2: Create a lightweight container with Nginx to serve the Angular application
FROM nginx:1.25.3-alpine as production
# Copy the built Angular application from the previous stage to the Nginx webroot directory
COPY --from=build /app/dist/angular-16-crud/ /usr/share/nginx/html
# Expose port 80
EXPOSE 80
# Start Nginx upon container startup
CMD ["nginx", "-g", "daemon off;"]
