apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: global-role-binding
  namespace: exam
subjects:
- kind: ServiceAccount
  name: global-user
  namespace: default
roleRef:
  kind: Role
  name: global-role
  apiGroup: rbac.authorization.k8s.io
