apiVersion: v1
kind: ResourceQuota
metadata:
  name: exam-resource-quota
  namespace: exam
spec:
  hard:
    pods: "12"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi