apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-reader-binding
  namespace: exam 
subjects:
- kind: ServiceAccount
  name: user1
  namespace: default
roleRef:
  kind: Role
  name: pod-list-reader
  apiGroup: rbac.authorization.k8s.io
